export const ipcChannels = {
  getAppReadiness: 'app:get-readiness',
  listProfiles: 'profiles:list',
  createProfile: 'profiles:create',
  updateProfile: 'profiles:update',
  deleteProfile: 'profiles:delete',
  selectActiveProfile: 'profiles:select-active',
  setDefaultProfile: 'profiles:set-default',
  getRuntimeConfig: 'runtime:get-config',
  updateRuntimePaths: 'runtime:update-paths',
  importLegacyProfiles: 'profiles:import-legacy',
  dismissLegacyImport: 'profiles:dismiss-legacy-import',
  listEc2Instances: 'ec2:list-instances',
  listTunnelTargets: 'tunnel:list-targets',
  openTunnelSession: 'tunnel:open-session',
  closeTunnelSession: 'tunnel:close-session',
  openSsmSession: 'ssm:open-session',
  sendSessionInput: 'ssm:send-input',
  resizeSession: 'ssm:resize-session',
  closeSession: 'ssm:close-session',
  sessionOutput: 'ssm:session-output',
  sessionExit: 'ssm:session-exit',
  sessionError: 'ssm:session-error',
  tunnelLog: 'tunnel:log',
  tunnelExit: 'tunnel:exit',
  tunnelError: 'tunnel:error'
} as const
